### ISSUE TITLE
Camera as entity

### ISSUE THREAD

**Issue by christopho** [christopho/solarus#762]
The camera is an entity in 1.5. This issue keeps track of the remaining work to do.
- [x] map:get_camera()
- [x] Add functions camera:start_tracking(entity) and camera:start_manual()
- [x] Add function game:set_suspended()
- [x] Test a scripted movement on the camera (#484)
- [x] Allow to resize the camera and set its coordinates on screen, for example to reserve a part of the screen to the hud like TLOZ or LA (#531)
- [x] Test an earthquake effect on the map (#531)
- [x] Add function camera:get_position_to_track(entity / x, y) to apply constraints (separators and/or map limits) to given coordinates. Useful to make movements.
- [x] Automatically switch to manual mode when starting a movement on the camera
- [x] Documentation
- [x] Deprecate map:get_camera_position(), map:move_camera() and map:on_camera_back()
- [x] Clean code

**Comment by christopho** [comment]
@wrightmat @Diarandor @Maxs1789 What would you think of this camera API proposal? http://www.solarus-games.org/doc/1.5/lua_api_camera.html

**Comment by Diarandor** [comment]
For me that's fine (I don't plan to use more than those functions, at least for now). If I have some idea I will tell you.

@Christopho: Will it be possible to move the camera "out" of the map?
Currently the camera stays inside the map, I mean, it's not possible to make a quake effect if the map has too small size because that obstructs the camera movement. I suppose that will change with the camera as entity, and if so, that would be very useful for quake effects.

**Comment by christopho** [comment]
@Diarandor Yes, it will be possible. You will be able to create a movement corresponding to the quake effect, call movement:set_ignore_obstacles(true) and start it on the camera.
Parts that are outside the map will be displayed with the background color of the tileset.

**Comment by wrightmat** [comment]
@christopho This should work very well for my purposes! I would primarily use the new functionality for cutscenes. My understanding is that I could use camera:start_tracking(npc) and it would move to that npc and follow it until I change the tracking state again, is that correct? If so, that would work perfectly for me.

I'm wondering if it would be possible to simplify this a bit and replace camera:start_tracking(entity), camera:start_manual and camera:get_tracked_entity with the functions camera:set_state(state, [entity]) and camera:get_state(return state, [entity]) with state being either manual or tracking right now (with room to grow if necessary in the future) and entity being the tracked entity where applicable? Then its state would be treated similarly to the hero's.

**Comment by wrightmat** [comment]
Also, semantic versioning calls for a deprecation of functionality for at least one minor or major release before complete removal. Therefore, I would keep map:move_camera() and map:get_camera_position() in the API, marked as deprecated, for Solarus 1.5 and remove them completely in 1.6.

**Comment by christopho** [comment]
Ok to deprecate these functions in 1.5 and remove them in 1.6.

There is no hero:set_state() function, there is a roughly a function hero:start_*() for each state. So the current proposal is actually closer to what is done with the hero. The idea is indeed to treat them similarly. We can add a function camera:get_state(), yes.

Thanks for the feedback!

**Comment by Diarandor** [comment]
This is a silly thing but I just want to point out that, although the camera will be an entity, it should not be returned by the functions like map:get_entities() or similars.

**Comment by christopho** [comment]
I don't really agree indeed, I prefer to avoid adding an exception. A camera is something that has coordinates on the map so it should be treated like other entities.

**Comment by Diarandor** [comment]
Yes, I agree on that the camera should be treated as any entity. Although for practical reasons, when we make a loop with map:get_entities_in_rectangle(...) or with map:get_entities(), we rarely would need to get the camera since it has a different nature than other entities, and we usually want to get other entities to detect collisions or for other things like that. But it's ok anyway, it does not really matter at all.

**Comment by wrightmat** [comment]
I could see it not being in map:get_entities_in_rectangle() - what would the coordinates of the camera be anyway? The origin point of the camera view (0,0 in most cases)? Isn't it technically above the hero and the rest of the map?

Would having it return in map:get_entities() and not map:get_entities_in_rectangle() just be confusing, or a compromise?

**Comment by Morwenn** [comment]
Maybe allow users to pass a list of entities to exclude to the functions so that the passed entities are not returned? Basically make the function perform a set difference between the raw results and the exclude list before actually returning.

**Comment by christopho** [comment]
The coordinates of a camera are the coordinates of the upper left corner of the rectangle they show. Its size is the size of the rectangle they show.

It has no name, so map:get_entities(prefix) will never return it if you pass a non-empty prefix.
Also, note that there is now a function map:get_entities_by_type() that can be useful.

The camera is placed on the highest layer of the map. Which reminds me that functions like map:get_entities_in_rectangle() should probably take an additional layer parameter (optional).
Then, a way to avoid the camera in these functions can be to create one more layer than necessary.

With all these possibilities, I don't think it is useful to add exceptions or special exclusion filters. I can at least put a remark in the doc to remind users that all types of entities can be returned. It can be surprising because of the camera, but not only that. I was also surprised by some other unexpected entities in my tests, like separators and destinations.

**Comment by Diarandor** [comment]
Another solution could be to add an optional extra parameter to these functions to allow to exclude the camera and separators if desired.

Something like:
map:get_entities("", true) 
or equivalently
map:get_entities(nil, true),
and similarly
map:get_entities_in_rectangle(x,y,width,height,  true)
to exclude the camera and separators if desired. That would come in handy.

**Comment by christopho** [comment]
Too specific. What exactly you want to exclude depends on the usage.

**Comment by Diarandor** [comment]
Yes, you are right, it's a completely unclear if other entities like teleporters should be excluded. Maybe what Morwenn said could be the best option, an exclussion list.

**Comment by Diarandor** [comment]
Or maybe we should just forget these exclussions and return all types (that could be done in Lua anyway).

**Comment by christopho** [comment]
Maybe we should figure out a way to chain successive filters? Like filter by rectangle, then by layer, then by type…  It would be flexible and powerful, but I don't know how to present this in the API.

**Comment by christopho** [comment]
It is also easy to do in pure Lua so maybe it is not worth it.

**Comment by Morwenn** [comment]
inb4 SQL dialect to select entities.

**Comment by Diarandor** [comment]
Then a nice and flexible choice could be an optional list of optional properties (some of them lists too). Something like map:get_entities(list)
with
list = {
prefix = ...,
rectangle = {x,y,width,height},
layer = ..., 
types = {...},
excluded_types = {...}
}

What do you think? We could even remove the function get_entities_in_rectangle to shorten the API.

**Comment by christopho** [comment]
I am starting to like it :)
Of course, let's also allow custom predicates.

map:get_entities(condition)
condition is either a string (for compatibility: a prefix) or a table of predicates, where each predicate is a key-value pair of the table:
- prefix = ...,
- pattern = ...,  -- match the name with a Lua pattern
- rectangle = {x,y,width,height},
- layer = ...,
- type = ...,
- types = { ... },
- excluded_types = { ... },
- custom predicate function(s) (entity -> boolean)

For example, if you want to kill all enemies whose life is below 10 in the screen, like with a magic attack:

    for enemy in map:get_entities({
      rectangle = camera:get_bounding_box(),
      type = "enemy",
      function(e) return e:get_life() < 10 end,
    }) do
        enemy:set_life(0)
    end

**Comment by christopho** [comment]
Done
